"use client";

import { type FormEvent, useEffect, useMemo, useState } from "react";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { ConfirmDialog } from "@/components/ui/ConfirmDialog";
import { Input } from "@/components/ui/Input";
import { Modal } from "@/components/ui/Modal";
import { PageHeader } from "@/components/ui/PageHeader";
import { Pagination } from "@/components/ui/Pagination";
import { Select } from "@/components/ui/Select";
import { EmptyState, ErrorState, LoadingState } from "@/components/ui/StateDisplay";
import { Table, type TableColumn } from "@/components/ui/Table";
import { categoryApi } from "@/features/categories/category.api";
import type { Category } from "@/features/categories/category.types";
import { subCategoryApi } from "@/features/catalog/catalog.api";
import type { CatalogStatus, SubCategory, SubCategoryPayload } from "@/features/catalog/catalog.types";
import { getApiErrorMessage, getApiFieldErrors } from "@/lib/api";
import { formatDate } from "@/lib/utils";
import type { Pagination as PaginationData } from "@/types/api";

const initialPagination: PaginationData = { page: 1, limit: 20, total: 0, totalPages: 0 };
const parentCategory = (record: SubCategory) => typeof record.category === "string" ? null : record.category;

export default function SubCategoriesPage() {
  const [records,setRecords]=useState<SubCategory[]>([]); const [categories,setCategories]=useState<Category[]>([]); const [pagination,setPagination]=useState(initialPagination); const [page,setPage]=useState(1); const [search,setSearch]=useState(""); const [query,setQuery]=useState(""); const [categoryId,setCategoryId]=useState(""); const [status,setStatus]=useState<CatalogStatus|"">(""); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [feedback,setFeedback]=useState<string|null>(null); const [editing,setEditing]=useState<SubCategory|null>(null); const [formOpen,setFormOpen]=useState(false); const [deactivating,setDeactivating]=useState<SubCategory|null>(null); const [pending,setPending]=useState(false); const [reload,setReload]=useState(0);
  useEffect(()=>{const id=window.setTimeout(()=>{setQuery(search.trim());setPage(1)},300);return()=>window.clearTimeout(id)},[search]);
  useEffect(()=>{categoryApi.list({page:1,limit:100,status:"active"}).then(data=>setCategories(data.categories)).catch(reason=>setError(getApiErrorMessage(reason,"Unable to load active categories.")))},[]);
  useEffect(()=>{let active=true;subCategoryApi.list({page,limit:20,search:query||undefined,categoryId:categoryId||undefined,status}).then(data=>{if(active){setRecords(data.subCategories);setPagination(data.pagination);setError(null)}}).catch(reason=>{if(active)setError(getApiErrorMessage(reason,"Unable to load sub-categories."))}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[categoryId,page,query,reload,status]);
  const deactivate=async()=>{if(!deactivating)return;setPending(true);try{await subCategoryApi.deactivate(deactivating._id);setFeedback("Sub-category deactivated successfully.");setDeactivating(null);setReload(v=>v+1)}catch(reason){setError(getApiErrorMessage(reason,"Unable to deactivate sub-category."));setDeactivating(null)}finally{setPending(false)}};
  const activate=async(record:SubCategory)=>{try{await subCategoryApi.update(record._id,{status:"active"});setFeedback("Sub-category activated successfully.");setReload(v=>v+1)}catch(reason){setError(getApiErrorMessage(reason,"Unable to activate sub-category."))}};
  const columns:Array<TableColumn<SubCategory>>=[{key:"name",header:"Sub-category",render:r=><span className="font-semibold text-neutral-950">{r.name}</span>},{key:"category",header:"Parent Category",render:r=>parentCategory(r)?.name||"Unavailable"},{key:"slug",header:"Slug",render:r=><code className="text-xs">{r.slug}</code>},{key:"status",header:"Status",render:r=><Badge tone={r.status==="active"?"active":"inactive"}>{r.status}</Badge>},{key:"created",header:"Created",render:r=>formatDate(r.createdAt)},{key:"actions",header:<span className="sr-only">Actions</span>,className:"text-right",render:r=><div className="flex justify-end gap-1"><Button variant="ghost" size="sm" onClick={()=>{setEditing(r);setFormOpen(true)}}>Edit</Button>{r.status==="active"?<Button variant="ghost" size="sm" className="text-[#7A1F2B]" onClick={()=>setDeactivating(r)}>Deactivate</Button>:<Button variant="ghost" size="sm" onClick={()=>void activate(r)}>Activate</Button>}</div>}];
  return <div className="mx-auto w-full max-w-[1500px]"><PageHeader title="Sub-categories" description="Manage catalog sub-categories and their parent Category." actions={<Button onClick={()=>{setEditing(null);setFormOpen(true)}}>+ Add Sub-category</Button>}/>{feedback?<div className="mb-4 border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800">{feedback}</div>:null}{error&&records.length?<div className="mb-4 border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{error}</div>:null}<section className="overflow-hidden rounded-lg border border-neutral-200 bg-white"><div className="grid gap-3 border-b p-4 md:grid-cols-[1fr_240px_200px]"><Input placeholder="Search sub-categories" value={search} onChange={e=>setSearch(e.target.value)}/><Select value={categoryId} onChange={e=>{setPage(1);setCategoryId(e.target.value)}}><option value="">All categories</option>{categories.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</Select><Select value={status} onChange={e=>{setPage(1);setStatus(e.target.value as CatalogStatus|"")}}><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></Select></div>{loading?<LoadingState label="Loading sub-categories"/>:error&&!records.length?<ErrorState message={error} onRetry={()=>setReload(v=>v+1)}/>:records.length?<><Table columns={columns} rows={records} rowKey={r=>r._id}/><Pagination page={pagination.page} totalPages={pagination.totalPages} total={pagination.total} pageSize={pagination.limit} onPageChange={setPage}/></>:<EmptyState title="No sub-categories found" description="Add a sub-category or change the current filters."/>}</section>{formOpen?<SubCategoryForm key={editing?._id??"new"} record={editing} categories={categories} onClose={()=>{setFormOpen(false);setEditing(null)}} onSaved={message=>{setFeedback(message);setReload(v=>v+1)}}/>:null}<ConfirmDialog isOpen={Boolean(deactivating)} title="Deactivate sub-category" description={`Deactivate ${deactivating?.name??"this sub-category"}? It can be reactivated later.`} confirmLabel="Deactivate" tone="danger" isConfirming={pending} onClose={()=>setDeactivating(null)} onConfirm={()=>void deactivate()}/></div>;
}

function SubCategoryForm({record,categories,onClose,onSaved}:{record:SubCategory|null;categories:Category[];onClose:()=>void;onSaved:(message:string)=>void}){const current=record?parentCategory(record):null;const options=useMemo(()=>current&&!categories.some(c=>c._id===current._id)?[current,...categories]:categories,[categories,current]);const[name,setName]=useState(record?.name??"");const[slug,setSlug]=useState(record?.slug??"");const[categoryId,setCategoryId]=useState(current?._id??"");const[status,setStatus]=useState<CatalogStatus>(record?.status??"active");const[errors,setErrors]=useState<Record<string,string>>({});const[requestError,setRequestError]=useState<string|null>(null);const[saving,setSaving]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();const next:Record<string,string>={};if(!name.trim())next.name="Name is required.";if(!categoryId)next.categoryId="Category is required.";setErrors(next);if(Object.keys(next).length)return;setSaving(true);try{const payload:SubCategoryPayload={name:name.trim(),categoryId,status,...(slug.trim()?{slug:slug.trim()}:{})};if(record)await subCategoryApi.update(record._id,payload);else await subCategoryApi.create(payload);onSaved(`Sub-category ${record?"updated":"created"} successfully.`);onClose()}catch(reason){setErrors(getApiFieldErrors(reason));setRequestError(getApiErrorMessage(reason,"Unable to save sub-category."))}finally{setSaving(false)}};return <Modal isOpen onClose={onClose} closeOnBackdrop={!saving} title={`${record?"Edit":"Add"} Sub-category`} footer={<><Button variant="secondary" disabled={saving} onClick={onClose}>Cancel</Button><Button form="subcategory-form" type="submit" isLoading={saving}>Save</Button></>}><form id="subcategory-form" className="space-y-4" onSubmit={submit}>{requestError?<div className="bg-red-50 p-3 text-sm text-red-800">{requestError}</div>:null}<Select label="Parent Category" value={categoryId} onChange={e=>setCategoryId(e.target.value)} error={errors.categoryId} required><option value="">Select Category</option>{options.map(c=><option key={c._id} value={c._id}>{c.name}{c.status==="inactive"?" (Inactive)":""}</option>)}</Select><Input label="Sub-category Name" value={name} onChange={e=>setName(e.target.value)} error={errors.name} maxLength={100} required/><Input label="Slug" value={slug} onChange={e=>setSlug(e.target.value)} error={errors.slug} maxLength={120} hint="Optional; generated by the backend when omitted."/><Select label="Status" value={status} onChange={e=>setStatus(e.target.value as CatalogStatus)} error={errors.status}><option value="active">Active</option><option value="inactive">Inactive</option></Select></form></Modal>}
