"use client";
/* eslint-disable react-hooks/set-state-in-effect */

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { PageHeader } from "@/components/ui/PageHeader";
import { Select } from "@/components/ui/Select";
import { Textarea } from "@/components/ui/Textarea";
import { categoryApi } from "@/features/categories/category.api";
import { colourApi, fabricApi, fitApi, sizeSetApi, subCategoryApi } from "@/features/catalog/catalog.api";
import type { Category, Colour, Fabric, Fit, SizeSet, SubCategory } from "@/features/catalog/catalog.types";
import { getApiErrorMessage } from "@/lib/api";
import { collectAllPages } from "@/lib/pagination";
import { formatMinorCurrency, previewGeneratedSku } from "@/lib/utils";
import { productApi } from "./product.api";
import type { CatalogStatus, Product, ProductPayload, ProductUpdatePayload } from "./product.types";

type ColourDraft = { key: string; colourId: string; productCode: string; sizeSetIds: string[]; status: CatalogStatus };
const minorFromRupees = (value: string) => { if (!/^\d+(?:\.\d{1,2})?$/.test(value.trim())) return null; const [whole, decimal = ""] = value.trim().split("."); const minor = Number(whole) * 100 + Number(decimal.padEnd(2, "0")); return Number.isSafeInteger(minor) ? minor : null; };
const idOf = (value: string | { _id: string }) => typeof value === "string" ? value : value._id;

export function ProductForm({ mode, product }: { mode: "create" | "edit"; product?: Product }) {
  const router = useRouter();
  const [step, setStep] = useState(1);
  const [name, setName] = useState(product?.name ?? ""); const [description, setDescription] = useState(product?.description ?? "");
  const [categoryId, setCategoryId] = useState(product ? idOf(product.category) : ""); const [subCategoryId, setSubCategoryId] = useState(product ? idOf(product.subCategory) : "");
  const [fitId, setFitId] = useState(product ? idOf(product.fitId) : ""); const [fabricId, setFabricId] = useState(product ? idOf(product.fabricId) : "");
  const [mrp, setMrp] = useState(product ? (product.mrpPerPieceMinor / 100).toFixed(2) : ""); const [status, setStatus] = useState<CatalogStatus>(product?.status ?? "active");
  const [colourDrafts, setColourDrafts] = useState<ColourDraft[]>([{ key: crypto.randomUUID(), colourId: "", productCode: "", sizeSetIds: [], status: "active" }]);
  const [categories, setCategories] = useState<Category[]>([]); const [subCategories, setSubCategories] = useState<SubCategory[]>([]); const [colours, setColours] = useState<Colour[]>([]); const [fits, setFits] = useState<Fit[]>([]); const [fabrics, setFabrics] = useState<Fabric[]>([]); const [sizeSets, setSizeSets] = useState<SizeSet[]>([]);
  const [loadingMasters, setLoadingMasters] = useState(true); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);

  useEffect(() => { let active = true; Promise.all([
    collectAllPages({ fetchPage: (page, limit) => categoryApi.list({ page, limit, status: "active" }), getItems: (data) => data.categories }),
    collectAllPages({ fetchPage: (page, limit) => colourApi.list({ page, limit, status: "active" }), getItems: (data) => data.colours }),
    collectAllPages({ fetchPage: (page, limit) => fitApi.list({ page, limit, status: "active" }), getItems: (data) => data.fits }),
    collectAllPages({ fetchPage: (page, limit) => fabricApi.list({ page, limit, status: "active" }), getItems: (data) => data.fabrics }),
    collectAllPages({ fetchPage: (page, limit) => sizeSetApi.list({ page, limit, status: "active" }), getItems: (data) => data.sizeSets }),
  ]).then(([categoryData, colourData, fitData, fabricData, sizeSetData]) => { if (!active) return; setCategories(categoryData); setColours(colourData); setFits(fitData); setFabrics(fabricData); setSizeSets(sizeSetData); }).catch((reason) => { if (active) setError(getApiErrorMessage(reason, "Unable to load Product masters.")); }).finally(() => { if (active) setLoadingMasters(false); }); return () => { active = false; }; }, []);
  useEffect(() => { if (!categoryId) { setSubCategories([]); setSubCategoryId(""); return; } let active = true; collectAllPages({ fetchPage: (page, limit) => subCategoryApi.list({ page, limit, status: "active", categoryId }), getItems: (data) => data.subCategories }).then((data) => { if (active) { setSubCategories(data); setSubCategoryId((current) => data.some((entry) => entry._id === current) ? current : ""); } }).catch((reason) => { if (active) setError(getApiErrorMessage(reason, "Unable to load Sub-categories.")); }); return () => { active = false; }; }, [categoryId]);

  const moneyMinor = minorFromRupees(mrp); const selected = <T extends { _id: string }>(items: T[], value: string) => items.find((entry) => entry._id === value);
  const basicValid = Boolean(name.trim() && categoryId && subCategoryId && fitId && fabricId && moneyMinor !== null);
  const coloursValid = colourDrafts.length > 0 && colourDrafts.every((entry) => entry.colourId && entry.productCode.trim() && entry.sizeSetIds.length > 0) && new Set(colourDrafts.map((entry) => entry.colourId)).size === colourDrafts.length;
  const expectedSkus = useMemo(() => colourDrafts.flatMap((entry) => entry.sizeSetIds.map((sizeSetId) => { const sizeSet = selected(sizeSets, sizeSetId); return { colour: selected(colours, entry.colourId), productCode: entry.productCode, sizeSet, sku: previewGeneratedSku(entry.productCode, sizeSet?.label ?? "") }; })), [colourDrafts, colours, sizeSets]);

  const submit = async (event: FormEvent) => { event.preventDefault(); setError(null); if (!basicValid) { setError("Complete all required Product fields and enter a valid rupee amount with at most two decimals."); setStep(1); return; } if (mode === "create" && !coloursValid) { setError("Add at least one unique Colour, Product Code, and Size Set."); setStep(2); return; } setSaving(true); try { if (mode === "edit" && product) { const payload: ProductUpdatePayload = { name: name.trim(), description: description.trim(), categoryId, subCategoryId, fitId, fabricId, mrpPerPieceMinor: moneyMinor!, status }; await productApi.update(product._id, payload); router.replace(`/products/${product._id}`); } else { const payload: ProductPayload = { name: name.trim(), description: description.trim() || undefined, categoryId, subCategoryId, fitId, fabricId, mrpPerPieceMinor: moneyMinor!, status, productColours: colourDrafts.map((entry) => ({ colourId: entry.colourId, productCode: entry.productCode.trim(), status: entry.status, skus: entry.sizeSetIds.map((sizeSetId) => ({ sizeSetId, status: entry.status })) })) }; const created = await productApi.create(payload); router.replace(`/products/${created.product._id}`); } } catch (reason) { setError(getApiErrorMessage(reason, `Unable to ${mode === "create" ? "create" : "save"} the Product.`)); } finally { setSaving(false); } };

  const basicFields = <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3"><Input label="Product Name" value={name} onChange={(event) => setName(event.target.value)} required maxLength={150} /><Select label="Category" value={categoryId} onChange={(event) => setCategoryId(event.target.value)} required disabled={loadingMasters}><option value="">Select Category</option>{categories.map((entry) => <option key={entry._id} value={entry._id}>{entry.name}</option>)}</Select><Select label="Sub-category" value={subCategoryId} onChange={(event) => setSubCategoryId(event.target.value)} required disabled={!categoryId}><option value="">Select Sub-category</option>{subCategories.map((entry) => <option key={entry._id} value={entry._id}>{entry.name}</option>)}</Select><Select label="Fit" value={fitId} onChange={(event) => setFitId(event.target.value)} required><option value="">Select Fit</option>{fits.map((entry) => <option key={entry._id} value={entry._id}>{entry.name}</option>)}</Select><Select label="Fabric" value={fabricId} onChange={(event) => setFabricId(event.target.value)} required><option value="">Select Fabric</option>{fabrics.map((entry) => <option key={entry._id} value={entry._id}>{entry.name}</option>)}</Select><Input label="MRP per piece (₹)" value={mrp} onChange={(event) => setMrp(event.target.value)} inputMode="decimal" placeholder="999.00" required error={mrp && moneyMinor === null ? "Use a non-negative amount with at most two decimals." : undefined} /><Select label="Status" value={status} onChange={(event) => setStatus(event.target.value as CatalogStatus)}><option value="active">Active</option><option value="inactive">Inactive</option></Select><div className="md:col-span-2 xl:col-span-3"><Textarea label="Description" value={description} onChange={(event) => setDescription(event.target.value)} maxLength={5000} /></div></div>;
  if (mode === "edit") return <div className="mx-auto w-full max-w-6xl"><PageHeader title="Edit Product" description="Edit finalized Product fields. Colours, images and immutable SKUs are managed on Product details." actions={<Button variant="secondary" onClick={() => router.push(`/products/${product?._id}`)}>Cancel</Button>} /><form onSubmit={submit} className="space-y-6 rounded-xl border border-neutral-200 bg-white p-6">{error ? <ErrorBanner message={error} /> : null}{basicFields}<div className="flex justify-end"><Button type="submit" isLoading={saving}>Save Changes</Button></div></form></div>;

  return <div className="mx-auto w-full max-w-[1400px]"><PageHeader title="Add Product Manually" description="Create the Product, its Colours and backend-generated immutable SKUs." /><form onSubmit={submit} className="overflow-hidden rounded-xl border border-neutral-200 bg-white"><div className="grid grid-cols-3 border-b bg-neutral-50">{["Product Details", "Colours & Size Sets", "Review & Submit"].map((label, index) => <button type="button" key={label} onClick={() => index + 1 < step && setStep(index + 1)} className={`border-b-2 px-4 py-5 text-sm font-semibold ${step === index + 1 ? "border-[#7A1F2B] text-[#7A1F2B]" : "border-transparent text-neutral-500"}`}><span className="mr-2 inline-grid h-7 w-7 place-items-center rounded-full bg-neutral-200">{index + 1}</span>{label}</button>)}</div><div className="p-6 sm:p-8">{error ? <ErrorBanner message={error} /> : null}{step === 1 ? <><h2 className="mb-5 text-lg font-semibold">Basic information</h2>{basicFields}</> : null}{step === 2 ? <ColourStep drafts={colourDrafts} setDrafts={setColourDrafts} colours={colours} sizeSets={sizeSets} /> : null}{step === 3 ? <ReviewStep name={name} category={selected(categories, categoryId)?.name} subCategory={selected(subCategories, subCategoryId)?.name} fit={selected(fits, fitId)?.name} fabric={selected(fabrics, fabricId)?.name} status={status} moneyMinor={moneyMinor} skus={expectedSkus} /> : null}</div><footer className="flex justify-between border-t bg-neutral-50 p-5"><Button variant="secondary" onClick={() => step === 1 ? router.push("/products") : setStep((value) => value - 1)}>{step === 1 ? "Back to Products" : "Back"}</Button>{step < 3 ? <Button onClick={() => { setError(null); if (step === 1 && !basicValid) return setError("Complete all required Product fields before continuing."); if (step === 2 && !coloursValid) return setError("Each unique Colour requires a Product Code and at least one Size Set."); setStep((value) => value + 1); }}>Next</Button> : <Button type="submit" isLoading={saving} loadingLabel="Creating Product">Create Product</Button>}</footer></form></div>;
}

function ErrorBanner({ message }: { message: string }) { return <div className="mb-5 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-800">{message}</div>; }
function ColourStep({ drafts, setDrafts, colours, sizeSets }: { drafts: ColourDraft[]; setDrafts: React.Dispatch<React.SetStateAction<ColourDraft[]>>; colours: Colour[]; sizeSets: SizeSet[] }) { return <><div className="mb-5 flex items-center justify-between"><div><h2 className="text-lg font-semibold">Product Colours and Size Sets</h2><p className="mt-1 text-sm text-neutral-500">Images can be uploaded per colour after creation.</p></div><Button variant="secondary" onClick={() => setDrafts((current) => [...current, { key: crypto.randomUUID(), colourId: "", productCode: "", sizeSetIds: [], status: "active" }])}>Add Colour</Button></div><div className="space-y-4">{drafts.map((draft, index) => <section key={draft.key} className="rounded-lg border border-neutral-200 p-5"><div className="grid gap-4 md:grid-cols-3"><Select label={`Colour ${index + 1}`} value={draft.colourId} onChange={(event) => setDrafts((current) => current.map((entry) => entry.key === draft.key ? { ...entry, colourId: event.target.value } : entry))} required><option value="">Select Colour</option>{colours.map((entry) => <option disabled={drafts.some((other) => other.key !== draft.key && other.colourId === entry._id)} key={entry._id} value={entry._id}>{entry.name}</option>)}</Select><Input label="Product Code" value={draft.productCode} onChange={(event) => setDrafts((current) => current.map((entry) => entry.key === draft.key ? { ...entry, productCode: event.target.value } : entry))} placeholder="e.g. denim_black" required /><Select label="Status" value={draft.status} onChange={(event) => setDrafts((current) => current.map((entry) => entry.key === draft.key ? { ...entry, status: event.target.value as CatalogStatus } : entry))}><option value="active">Active</option><option value="inactive">Inactive</option></Select></div><div className="mt-4"><p className="mb-2 text-sm font-medium">Size Sets *</p><div className="flex flex-wrap gap-2">{sizeSets.map((sizeSet) => { const checked = draft.sizeSetIds.includes(sizeSet._id); return <label key={sizeSet._id} className={`cursor-pointer rounded-md border px-3 py-2 text-sm ${checked ? "border-[#7A1F2B] bg-red-50" : "border-neutral-200"}`}><input className="mr-2" type="checkbox" checked={checked} onChange={() => setDrafts((current) => current.map((entry) => entry.key === draft.key ? { ...entry, sizeSetIds: checked ? entry.sizeSetIds.filter((value) => value !== sizeSet._id) : [...entry.sizeSetIds, sizeSet._id] } : entry))} />{sizeSet.label} · {sizeSet.pieceCount} pcs</label>; })}</div></div>{drafts.length > 1 ? <Button className="mt-4" size="sm" variant="ghost" onClick={() => setDrafts((current) => current.filter((entry) => entry.key !== draft.key))}>Remove Colour</Button> : null}</section>)}</div></>; }
function ReviewStep({ name, category, subCategory, fit, fabric, status, moneyMinor, skus }: { name: string; category?: string; subCategory?: string; fit?: string; fabric?: string; status: string; moneyMinor: number | null; skus: Array<{ colour?: Colour; productCode: string; sizeSet?: SizeSet; sku: string }> }) { return <><h2 className="text-lg font-semibold">Review & Submit</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Product", name], ["Category", category], ["Sub-category", subCategory], ["MRP per piece", moneyMinor === null ? "—" : formatMinorCurrency(moneyMinor)], ["Fit", fit], ["Fabric", fabric], ["Status", status], ["SKUs", String(skus.length)]].map(([label, value]) => <div key={label} className="rounded-lg border bg-neutral-50 p-4"><p className="text-xs uppercase tracking-wide text-neutral-500">{label}</p><p className="mt-1 font-semibold">{value || "—"}</p></div>)}</div><div className="mt-6 overflow-x-auto rounded-lg border"><table className="min-w-full text-left text-sm"><thead className="bg-neutral-50 text-xs uppercase text-neutral-500"><tr>{["Colour", "Product Code", "Size Set", "Sizes", "Expected SKU"].map((value) => <th key={value} className="p-3">{value}</th>)}</tr></thead><tbody className="divide-y">{skus.map((entry, index) => <tr key={`${entry.sku}-${index}`}><td className="p-3">{entry.colour?.name}</td><td className="p-3"><code>{entry.productCode}</code></td><td className="p-3">{entry.sizeSet?.label}</td><td className="p-3">{entry.sizeSet?.sizes.join(", ")}</td><td className="p-3"><code>{entry.sku}</code></td></tr>)}</tbody></table></div></>; }
