"use client";

import Link from "next/link";
import { useRef, useState } from "react";
import { Button } from "@/components/ui/Button";
import { ConfirmDialog } from "@/components/ui/ConfirmDialog";
import { PageHeader } from "@/components/ui/PageHeader";
import { ApiError, getApiErrorMessage } from "@/lib/api";
import { formatDateTime, formatMinorCurrency } from "@/lib/utils";
import { productImportApi } from "./product.api";
import type { ProductImportBatch, ProductImportResult } from "./product.types";

const headers = ["Product Name", "Product Code", "SKU", "Category", "Product title", "Colour", "Size", "MRP", "Fit", "Pattern/Wash", "Fabric", "Sleeves", "Waist"];

export function ProductImportFlow() {
  const inputRef = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File | null>(null); const [batch, setBatch] = useState<ProductImportBatch | null>(null); const [result, setResult] = useState<ProductImportResult | null>(null); const [error, setError] = useState<string | null>(null); const [uploading, setUploading] = useState(false); const [applying, setApplying] = useState(false); const [confirming, setConfirming] = useState(false);
  const choose = (selected?: File) => { setError(null); setBatch(null); setResult(null); if (!selected) return setFile(null); if (!selected.name.toLowerCase().endsWith(".xlsx")) { setFile(null); return setError("Only .xlsx files are supported."); } if (selected.size > 10 * 1024 * 1024) { setFile(null); return setError("The XLSX file cannot exceed 10 MiB."); } setFile(selected); };
  const preview = async () => { if (!file || uploading) return; setUploading(true); setError(null); try { setBatch(await productImportApi.preview(file)); } catch (reason) { setError(getApiErrorMessage(reason, "Unable to create Product Import preview.")); } finally { setUploading(false); } };
  const apply = async () => { if (!batch || batch.status !== "VALID" || batch.invalidRows > 0) return; setApplying(true); setError(null); try { const applied = await productImportApi.apply(batch.id); setResult(applied); setBatch((current) => current ? { ...current, status: "APPLIED", appliedAt: applied.appliedAt, result: applied } : current); setConfirming(false); } catch (reason) { const fallback = reason instanceof ApiError && reason.status === 409 ? "The import can no longer be applied because catalog data changed or this batch was already processed. Upload and review the sheet again." : "Unable to apply Product Import."; setError(getApiErrorMessage(reason, fallback)); setConfirming(false); } finally { setApplying(false); } };

  if (result) return <div className="mx-auto w-full max-w-[1400px]"><PageHeader title="Product XLSX Import Result" description="The persisted preview batch was applied successfully." /><section className="rounded-xl border border-green-300 bg-green-50 p-6"><h2 className="text-xl font-semibold text-green-900">Import completed successfully</h2><p className="mt-2 text-sm text-green-800">Completed {formatDateTime(result.appliedAt)}</p></section><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[["Products created", result.createdProducts], ["Products reused", result.existingProducts], ["Product Colours created", result.createdProductColours], ["Product Colours reused", result.existingProductColours], ["SKUs created", result.createdVariants], ["SKUs reused", result.existingVariants]].map(([label, value]) => <Summary key={String(label)} label={String(label)} value={Number(value)} />)}</div><div className="mt-6 flex gap-3"><Button variant="secondary" onClick={() => { setFile(null); setBatch(null); setResult(null); }}>Import another file</Button><Link href="/products"><Button>View Products</Button></Link></div></div>;

  return <div className="mx-auto w-full max-w-[1500px]"><PageHeader title="Product Listing XLSX" description="Upload, validate and review the complete batch before atomic Apply." actions={<Link href="/products/new"><Button variant="secondary">Back to Add Product</Button></Link>} />{error ? <div className="mb-5 rounded-md border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div> : null}{!batch ? <div className="grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><section className="rounded-xl border bg-white p-6"><h2 className="text-lg font-semibold">Upload XLSX file</h2><button type="button" onClick={() => inputRef.current?.click()} className="mt-5 grid min-h-64 w-full place-items-center rounded-xl border-2 border-dashed border-[#7A1F2B]/35 bg-red-50/30 p-8 text-center"><span><span className="text-4xl text-[#7A1F2B]">⇧</span><strong className="mt-3 block">{file?.name ?? "Choose a Product Listing XLSX file"}</strong><span className="mt-2 block text-sm text-neutral-500">.xlsx only · maximum 10 MiB · 20,000 rows</span></span></button><input ref={inputRef} className="hidden" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={(event) => choose(event.target.files?.[0])} /><Button className="mt-5 w-full" disabled={!file} isLoading={uploading} onClick={preview}>Upload and Preview</Button></section><section className="rounded-xl border bg-white p-6"><h2 className="text-lg font-semibold">Finalized columns</h2><div className="mt-4 flex flex-wrap gap-2">{headers.map((header) => <span key={header} className="rounded bg-neutral-100 px-2.5 py-1.5 text-xs font-medium">{header}</span>)}</div><div className="mt-6 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900"><strong>Important</strong><p>All masters must already exist and be active. Invalid rows block the whole batch. Images and inventory are never imported here.</p></div></section></div> : <Preview batch={batch} onReset={() => { setBatch(null); setFile(null); }} onApply={() => setConfirming(true)} applying={applying} />}
  <ConfirmDialog isOpen={confirming} onClose={() => !applying && setConfirming(false)} onConfirm={apply} isConfirming={applying} title="Apply Product Import?" description="This applies the exact persisted preview as one atomic catalog transaction. It cannot be applied twice." confirmLabel="Apply Import" /></div>;
}

function Preview({ batch, onReset, onApply, applying }: { batch: ProductImportBatch; onReset: () => void; onApply: () => void; applying: boolean }) { const canApply = batch.status === "VALID" && batch.invalidRows === 0; return <><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Summary label="Total rows" value={batch.totalRows} /><Summary label="Valid rows" value={batch.validRows} tone="green" /><Summary label="Invalid rows" value={batch.invalidRows} tone={batch.invalidRows ? "red" : undefined} /><Summary label="Batch status" value={batch.status} /></div><div className="mt-5 flex flex-wrap justify-between gap-3"><Button variant="secondary" onClick={onReset}>Upload another file</Button><Button disabled={!canApply} isLoading={applying} onClick={onApply}>Apply Complete Batch</Button></div>{!canApply ? <p className="mt-3 rounded-md bg-amber-50 p-3 text-sm text-amber-900">Apply is disabled. Correct every error and upload the workbook again.</p> : null}{batch.errors.length ? <Issues title="Blocking errors" issues={batch.errors} tone="red" /> : null}{batch.warnings.length ? <Issues title="Warnings" issues={batch.warnings} tone="amber" /> : null}<section className="mt-6 overflow-hidden rounded-xl border bg-white"><div className="border-b p-5"><h2 className="font-semibold">Normalized preview</h2><p className="mt-1 text-sm text-neutral-500">Read-only backend-normalized values. Expires {formatDateTime(batch.expiresAt)}.</p></div><div className="overflow-x-auto"><table className="min-w-[1250px] w-full text-left text-sm"><thead className="bg-neutral-50 text-xs uppercase text-neutral-500"><tr>{["Row", "Product", "Category", "Sub-category", "Fit / Fabric", "MRP / piece", "Colour", "Product Code", "Size Set", "Expected SKU", "Status"].map((value) => <th className="p-3" key={value}>{value}</th>)}</tr></thead><tbody className="divide-y">{batch.normalizedRows.map((row) => <tr key={row.rowNumber} className={row.validationStatus === "INVALID" ? "bg-red-50" : ""}><td className="p-3">{row.rowNumber}</td><td className="p-3 font-medium">{row.productName || "—"}</td><td className="p-3">{row.categoryName || "—"}</td><td className="p-3">{row.subCategoryName || "—"}</td><td className="p-3">{row.fitName || "—"} / {row.fabricName || "—"}</td><td className="p-3">{formatMinorCurrency(row.mrpPerPieceMinor)}</td><td className="p-3">{row.colourName || "—"}</td><td className="p-3"><code>{row.expectedProductCode || row.productCode || "—"}</code></td><td className="p-3">{row.sizeSetLabel || "—"}</td><td className="p-3"><code>{row.expectedSku || "—"}</code></td><td className="p-3"><span className={`rounded px-2 py-1 text-xs font-semibold ${row.validationStatus === "VALID" ? "bg-green-100 text-green-800" : "bg-red-100 text-red-800"}`}>{row.validationStatus}</span></td></tr>)}</tbody></table></div></section></>; }
function Issues({ title, issues, tone }: { title: string; issues: ProductImportBatch["errors"]; tone: "red" | "amber" }) { return <section className={`mt-6 rounded-xl border p-5 ${tone === "red" ? "border-red-200 bg-red-50" : "border-amber-200 bg-amber-50"}`}><h2 className="font-semibold">{title} ({issues.length})</h2><div className="mt-3 max-h-60 overflow-auto space-y-2">{issues.map((issue, index) => <p key={`${issue.rowNumber}-${issue.code}-${index}`} className="text-sm"><strong>Row {issue.rowNumber} · {issue.field}</strong> — {issue.message}</p>)}</div></section>; }
function Summary({ label, value, tone }: { label: string; value: string | number; tone?: "green" | "red" }) { return <div className="rounded-xl border bg-white p-5"><p className="text-sm text-neutral-500">{label}</p><p className={`mt-2 text-2xl font-semibold ${tone === "green" ? "text-green-700" : tone === "red" ? "text-red-700" : "text-neutral-950"}`}>{value}</p></div>; }
