"use client";
/* eslint-disable react-hooks/set-state-in-effect */

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { PageHeader } from "@/components/ui/PageHeader";
import { Select } from "@/components/ui/Select";
import { Textarea } from "@/components/ui/Textarea";
import { categoryApi } from "@/features/categories/category.api";
import { colourApi, fabricApi, fitApi, subCategoryApi } from "@/features/catalog/catalog.api";
import type { Category, Colour, Fabric, Fit, SubCategory } from "@/features/catalog/catalog.types";
import { getApiErrorMessage } from "@/lib/api";
import { collectAllPages } from "@/lib/pagination";
import { formatMinorCurrency, previewGeneratedProductCode, previewGeneratedSku } from "@/lib/utils";
import { productApi } from "./product.api";
import type { CatalogStatus, Product, ProductPayload, ProductUpdatePayload } from "./product.types";

type ColourDraft = { key: string; colourId: string; sizes: string[]; status: CatalogStatus };
const minorFromRupees = (value: string) => { if (!/^\d+(?:\.\d{1,2})?$/.test(value.trim())) return null; const [whole, decimal = ""] = value.trim().split("."); const minor = Number(whole) * 100 + Number(decimal.padEnd(2, "0")); return Number.isSafeInteger(minor) && minor > 0 ? minor : null; };
const idOf = (value: string | { _id: string }) => typeof value === "string" ? value : value._id;

export function ProductForm({ mode, product }: { mode: "create" | "edit"; product?: Product }) {
  const router = useRouter(); const [step, setStep] = useState(1);
  const [name, setName] = useState(product?.name ?? ""); const [description, setDescription] = useState(product?.description ?? "");
  const [categoryId, setCategoryId] = useState(product ? idOf(product.category) : ""); const [subCategoryId, setSubCategoryId] = useState(product ? idOf(product.subCategory) : "");
  const [fitId, setFitId] = useState(product ? idOf(product.fitId) : ""); const [fabricId, setFabricId] = useState(product ? idOf(product.fabricId) : "");
  const [mrp, setMrp] = useState(product ? (product.mrpPerPieceMinor / 100).toFixed(2) : ""); const [status, setStatus] = useState<CatalogStatus>(product?.status ?? "active");
  const [drafts, setDrafts] = useState<ColourDraft[]>([{ key: crypto.randomUUID(), colourId: "", sizes: [""], status: "active" }]);
  const [categories, setCategories] = useState<Category[]>([]); const [subCategories, setSubCategories] = useState<SubCategory[]>([]); const [colours, setColours] = useState<Colour[]>([]); const [fits, setFits] = useState<Fit[]>([]); const [fabrics, setFabrics] = useState<Fabric[]>([]);
  const [loadingMasters, setLoadingMasters] = useState(true); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { let active = true; Promise.all([
    collectAllPages({ fetchPage: (page, limit) => categoryApi.list({ page, limit, status: "active" }), getItems: (data) => data.categories }),
    collectAllPages({ fetchPage: (page, limit) => colourApi.list({ page, limit, status: "active" }), getItems: (data) => data.colours }),
    collectAllPages({ fetchPage: (page, limit) => fitApi.list({ page, limit, status: "active" }), getItems: (data) => data.fits }),
    collectAllPages({ fetchPage: (page, limit) => fabricApi.list({ page, limit, status: "active" }), getItems: (data) => data.fabrics }),
  ]).then(([a, b, c, d]) => { if (active) { setCategories(a); setColours(b); setFits(c); setFabrics(d); } }).catch((reason) => active && setError(getApiErrorMessage(reason, "Unable to load Product masters."))).finally(() => active && setLoadingMasters(false)); return () => { active = false; }; }, []);
  useEffect(() => { if (!categoryId) { setSubCategories([]); setSubCategoryId(""); return; } let active = true; collectAllPages({ fetchPage: (page, limit) => subCategoryApi.list({ page, limit, status: "active", categoryId }), getItems: (data) => data.subCategories }).then((data) => { if (active) { setSubCategories(data); setSubCategoryId((current) => data.some((entry) => entry._id === current) ? current : ""); } }).catch((reason) => active && setError(getApiErrorMessage(reason, "Unable to load Sub-categories."))); return () => { active = false; }; }, [categoryId]);
  const selected = <T extends { _id: string }>(items: T[], value: string) => items.find((entry) => entry._id === value); const moneyMinor = minorFromRupees(mrp);
  const nameError = name && /\s/.test(name) ? "Product name cannot contain spaces." : undefined;
  const basicValid = Boolean(name && !nameError && categoryId && selected(categories, categoryId)?.sizeFamily && subCategoryId && fitId && fabricId && moneyMinor);
  const coloursValid = drafts.length > 0 && drafts.every((entry) => entry.colourId && entry.sizes.length && entry.sizes.every((size) => size.trim())) && new Set(drafts.map((entry) => entry.colourId)).size === drafts.length;
  const previews = useMemo(() => drafts.flatMap((entry) => { const colour = selected(colours, entry.colourId); const productCode = previewGeneratedProductCode(name, colour?.name ?? ""); return entry.sizes.map((size) => ({ colour, productCode, size, sku: previewGeneratedSku(productCode, size) })); }), [colours, drafts, name]);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(null); if (!basicValid) { setError(nameError || "Complete all required Product fields and configure the Category size family."); setStep(1); return; } if (mode === "create" && !coloursValid) { setError("Each unique Colour requires at least one Size input."); setStep(2); return; } setSaving(true); try { if (mode === "edit" && product) { const payload: ProductUpdatePayload = { name: name.toUpperCase(), description: description.trim(), categoryId, subCategoryId, fitId, fabricId, mrpPerPieceMinor: moneyMinor!, status }; await productApi.update(product._id, payload); router.replace(`/products/${product._id}`); } else { const payload: ProductPayload = { name: name.toUpperCase(), description: description.trim() || undefined, categoryId, subCategoryId, fitId, fabricId, mrpPerPieceMinor: moneyMinor!, status, productColours: drafts.map((entry) => ({ colourId: entry.colourId, status: entry.status, skus: entry.sizes.map((size) => ({ size: size.trim(), status: entry.status })) })) }; const created = await productApi.create(payload); router.replace(`/products/${created.product._id}`); } } catch (reason) { setError(getApiErrorMessage(reason, `Unable to ${mode === "create" ? "create" : "save"} the Product.`)); } finally { setSaving(false); } };
  const basic = <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3"><Input label="Product Name" value={name} onChange={(event) => setName(event.target.value.toUpperCase())} error={nameError} hint="Single word only; underscores and hyphens are allowed." required maxLength={150} /><Select label="Category" value={categoryId} onChange={(event) => setCategoryId(event.target.value)} required disabled={loadingMasters}><option value="">Select Category</option>{categories.map((entry) => <option key={entry._id} value={entry._id}>{entry.name}{entry.sizeFamily ? ` · ${entry.sizeFamily}` : " · REQUIRES SETUP"}</option>)}</Select><Select label="Sub-category" value={subCategoryId} onChange={(event) => setSubCategoryId(event.target.value)} required disabled={!categoryId}><option value="">Select Sub-category</option>{subCategories.map((entry) => <option key={entry._id} value={entry._id}>{entry.name}</option>)}</Select><Select label="Fit" value={fitId} onChange={(event) => setFitId(event.target.value)} required><option value="">Select Fit</option>{fits.map((entry) => <option key={entry._id} value={entry._id}>{entry.name}</option>)}</Select><Select label="Fabric" value={fabricId} onChange={(event) => setFabricId(event.target.value)} required><option value="">Select Fabric</option>{fabrics.map((entry) => <option key={entry._id} value={entry._id}>{entry.name}</option>)}</Select><Input label="MRP per piece (₹)" value={mrp} onChange={(event) => setMrp(event.target.value)} inputMode="decimal" required error={mrp && moneyMinor === null ? "MRP must be greater than zero with at most two decimals." : undefined} /><Select label="Status" value={status} onChange={(event) => setStatus(event.target.value as CatalogStatus)}><option value="active">Active</option><option value="inactive">Inactive</option></Select><div className="md:col-span-2 xl:col-span-3"><Textarea label="Product title / Description" value={description} onChange={(event) => setDescription(event.target.value)} maxLength={5000} /></div></div>;
  if (mode === "edit") return <div className="mx-auto w-full max-w-6xl"><PageHeader title="Edit Product" description="Identifiers remain immutable." /><form onSubmit={submit} className="space-y-6 rounded-xl border bg-white p-6">{error ? <ErrorBanner message={error} /> : null}{basic}<div className="flex justify-end"><Button type="submit" isLoading={saving}>Save Changes</Button></div></form></div>;
  return <div className="mx-auto w-full max-w-[1400px]"><PageHeader title="Add Product Manually" description="Product Code and SKU are generated by the backend." /><form onSubmit={submit} className="overflow-hidden rounded-xl border bg-white"><div className="grid grid-cols-3 border-b bg-neutral-50">{["Product Details", "Colours & Sizes", "Review & Submit"].map((label, index) => <button type="button" key={label} onClick={() => index + 1 < step && setStep(index + 1)} className={`border-b-2 px-4 py-5 text-sm font-semibold ${step === index + 1 ? "border-[#7A1F2B] text-[#7A1F2B]" : "border-transparent text-neutral-500"}`}>{index + 1}. {label}</button>)}</div><div className="p-6 sm:p-8">{error ? <ErrorBanner message={error} /> : null}{step === 1 ? basic : null}{step === 2 ? <ColourStep drafts={drafts} setDrafts={setDrafts} colours={colours} productName={name} /> : null}{step === 3 ? <Review previews={previews} name={name} mrp={moneyMinor} /> : null}</div><footer className="flex justify-between border-t bg-neutral-50 p-5"><Button variant="secondary" onClick={() => step === 1 ? router.push("/products") : setStep((value) => value - 1)}>Back</Button>{step < 3 ? <Button onClick={() => { if (step === 1 && !basicValid) return setError(nameError || "Complete all required fields and configure the Category size family."); if (step === 2 && !coloursValid) return setError("Each Colour requires at least one Size input."); setError(null); setStep((value) => value + 1); }}>Next</Button> : <Button type="submit" isLoading={saving}>Create Product</Button>}</footer></form></div>;
}

function ColourStep({ drafts, setDrafts, colours, productName }: { drafts: ColourDraft[]; setDrafts: React.Dispatch<React.SetStateAction<ColourDraft[]>>; colours: Colour[]; productName: string }) { return <><div className="mb-5 flex justify-between"><div><h2 className="text-lg font-semibold">Colours and Size inputs</h2><p className="text-sm text-neutral-500">Use ranges such as S-XL or 30-38, or an explicit comma-separated list.</p></div><Button variant="secondary" onClick={() => setDrafts((current) => [...current, { key: crypto.randomUUID(), colourId: "", sizes: [""], status: "active" }])}>Add Colour</Button></div><div className="space-y-4">{drafts.map((draft, index) => { const colour = colours.find((entry) => entry._id === draft.colourId); const code = previewGeneratedProductCode(productName, colour?.name ?? ""); return <section key={draft.key} className="rounded-lg border p-5"><div className="grid gap-4 md:grid-cols-3"><Select label={`Colour ${index + 1}`} value={draft.colourId} onChange={(event) => setDrafts((current) => current.map((entry) => entry.key === draft.key ? { ...entry, colourId: event.target.value } : entry))}><option value="">Select Colour</option>{colours.map((entry) => <option key={entry._id} disabled={drafts.some((other) => other.key !== draft.key && other.colourId === entry._id)} value={entry._id}>{entry.name}</option>)}</Select><Input label="Generated Product Code (preview)" value={code} readOnly hint="The backend resolves collision suffixes." /><Select label="Status" value={draft.status} onChange={(event) => setDrafts((current) => current.map((entry) => entry.key === draft.key ? { ...entry, status: event.target.value as CatalogStatus } : entry))}><option value="active">Active</option><option value="inactive">Inactive</option></Select></div><div className="mt-4 space-y-2">{draft.sizes.map((size, sizeIndex) => <div className="flex gap-2" key={sizeIndex}><Input label={sizeIndex === 0 ? "Size / Size Set" : undefined} value={size} onChange={(event) => setDrafts((current) => current.map((entry) => entry.key === draft.key ? { ...entry, sizes: entry.sizes.map((item, i) => i === sizeIndex ? event.target.value.toUpperCase() : item) } : entry))} placeholder="S-XL or 30-38" /><Button variant="ghost" disabled={draft.sizes.length === 1} onClick={() => setDrafts((current) => current.map((entry) => entry.key === draft.key ? { ...entry, sizes: entry.sizes.filter((_, i) => i !== sizeIndex) } : entry))}>Remove</Button></div>)}<Button size="sm" variant="secondary" onClick={() => setDrafts((current) => current.map((entry) => entry.key === draft.key ? { ...entry, sizes: [...entry.sizes, ""] } : entry))}>Add another Size Set</Button></div>{drafts.length > 1 ? <Button className="mt-4" size="sm" variant="ghost" onClick={() => setDrafts((current) => current.filter((entry) => entry.key !== draft.key))}>Remove Colour</Button> : null}</section>; })}</div></>; }
function Review({ previews, name, mrp }: { previews: Array<{ colour?: Colour; productCode: string; size: string; sku: string }>; name: string; mrp: number | null }) { return <><h2 className="text-lg font-semibold">Review</h2><p className="mt-2">{name} · {mrp ? formatMinorCurrency(mrp) : "—"}</p><div className="mt-5 overflow-x-auto rounded-lg border"><table className="min-w-full text-left text-sm"><thead><tr>{["Colour", "Generated Product Code", "Size input", "Generated SKU"].map((label) => <th className="p-3" key={label}>{label}</th>)}</tr></thead><tbody>{previews.map((entry, index) => <tr key={index} className="border-t"><td className="p-3">{entry.colour?.name}</td><td className="p-3"><code>{entry.productCode}</code></td><td className="p-3">{entry.size}</td><td className="p-3"><code>{entry.sku}</code></td></tr>)}</tbody></table></div></>; }
function ErrorBanner({ message }: { message: string }) { return <div className="mb-5 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-800">{message}</div>; }
